### ISSUE TITLE
Run tests without debug info

### ISSUE THREAD

**Issue by Snekatis** [bendyworks/bwoken#10] opened 2012-08-02 09:14 UTC
Hey, is there a way how to run tests without debug info? So basically that there will be just info about which test is currently running and if it passed or not.

Thanks

**Comment by listrophy** [comment] 2012-08-02 13:06
That would require writing a new formatter. Bwoken has a standard (i.e., show everything) formatter and a colorful (what you see when running bwoken) formatter. What you want can easily be achieved with a new formatter.

I'm not sure, however, if it's easy or even possible to specify a different formatter right now. That can certainly go on the list of proposed features. As always, pull requests welcome!

**Comment by Jaym3s** [comment] 2012-08-02 14:08
No, not at the moment. I think it would be nice to specify verbosity in
some sort of configuration file once we get that figured out.

On Thu, Aug 2, 2012 at 4:14 AM, Ondřej Štěpánek <
reply@reply.github.com

**Comment by listrophy** [comment] 2013-09-04 14:44
This is essentially a duplicate of #22, so I'm going to close it. I'll also add `--formatter=simple` to the list of requested formatters.

**Closed as completed by listrophy** 2013-09-04 14:44 UTC
Labels: enhancement
