### ISSUE TITLE
where to find result of logElementTree?

### ISSUE THREAD

**Issue by wbreeze** [bendyworks/bwoken#62] opened 2014-01-18 05:19 UTC
This is a question.  I have searched over these docs, issues, Apple docs, StackOverflow, blogs…  Am not finding an answer.

When a test calls, `UIAElement.logElementTree()`, where does the output go?  I have found png files in the results directory, but not any log output.  My console log shows:

```
Debug:  keyboard.typeString("user@example.com")
logElementTree: 
Debug:  tap scrollViews[0].secureTextFields[0]
```

Running with ruby 2.1.0, Gemfiles:

```
  specs:
    bwoken (2.0.0)
      coffee-script-source
      colorful
      execjs
      json_pure
      rake
      slop
    coffee-script-source (1.6.3)
    colorful (0.0.3)
    execjs (2.0.2)
    json_pure (1.8.1)
    rake (10.1.1)
    slop (3.4.7)
```

**Comment by listrophy** [comment] 2014-01-18 17:01
To my knowledge, `logElementTree` is not supported in bwoken. I'd like to apologize for wasting your time by not putting that in the README.

Closing, since this is a dupe of #14.

**Closed as completed by listrophy** 2014-01-18 17:01 UTC
