### ISSUE TITLE
Additional Install Instructions needed

### ISSUE THREAD

**Issue by mrdavidgagnon** [bendyworks/bwoken#36] opened 2013-09-20 08:58 UTC
Darn. I was so close to getting my xcode project up and runnign with travis ci, but recently when I work my way through the new (non rake based) install instructions, I get stuck at:

$ bwoken init
-bash: bwoken: command not found

Do I have to do something to enable bwoken as a shell command in OSX?

**Comment by michaelforrest** [comment] 2013-09-20 16:54
I have been struggling with this. The problem is that the master branch here has instructions for a work-in-progress version of this gem. 

[See here for the actual instructions](https://github.com/bendyworks/bwoken/tree/v1.3.0#installation).

To avoid confusion it would have been nice to implement the Rake migration on a feature branch instead of on master.

**Comment by listrophy** [comment] 2013-09-20 18:17
Two things:
1. Regarding @michaelforrest's comment, you should be able to still use `rake` to use bwoken. It will show a message indicating that it is deprecated, but should otherwise work normally (until it's removed in some later version).
2. Depending on how you have your system setup, you may need to prepend your call to `bwoken` with `bundle exec`. This is less than ideal of course, but if you run `bundle exec bwoken init`, whether it works or not gives me an idea of what might be going wrong.

**Comment by listrophy** [comment] 2013-09-20 18:19
Also, sorry about not including a link to [upgrading instructions](/bendyworks/bwoken/wiki/Upgrading-from-v1-to-v2) in the current readme. I'll fix that soon.

**Comment by listrophy** [comment] 2013-12-30 17:07
Is there an outstanding issue here? Or can I close this?

**Comment by mrdavidgagnon** [comment] 2014-01-02 11:30
close it

**Comment by listrophy** [comment] 2014-01-02 15:12
Thanks!

**Closed as completed by listrophy** 2014-01-02 15:12 UTC
